### ISSUE TITLE
Loading https://sparksvg.me seems to time out

### ISSUE THREAD

**Issue by Primigenus** [tgvashworth/sparksvg#10]
Since example code includes `//sparksvg.me` as the host, I assumed both protocols would be supported.

Tested with the following sparkline: http://sparksvg.me/line.svg?15,77,67,62,87,73,10,75,86,79,96,67,74,56,48,59,36 which we're using on https://q42.nl/over-q42 (scroll to the three large counters displaying real-time data) and https://sparksvg.me/line.svg?15,77,67,62,87,73,10,75,86,79,96,67,74,56,48,59,36

**Comment by tgvashworth** [comment]
Hey, thanks for pointing this out. I agree it should work over HTTPS. Haven't touched this repo in a long time so I'm afraid this is unlikely to be a quick fix, but I'll get to it soon. Probably will put Cloudflare in front of the domain.

**Comment by Primigenus** [comment]
Any progress on this?

**Comment by tgvashworth** [comment]
Unfortunately not, sorry, but thanks for the bump — this had fallen off my radar.

**Comment by tgvashworth** [comment]
Hi @Primigenus — I've just moved the nameservers over to Cloudflare which starts the process of enabling HTTPS. Will keep you updated!

**Comment by tgvashworth** [comment]
@Primigenus And, quicker than expected, https://sparksvg.me/test.html and your example seem to load now! Will close this — let me know if you have any trouble.
