### ISSUE TITLE
Zero values in sparkline dataset in Firefox

### ISSUE THREAD

**Issue by adactio** [tgvashworth/sparksvg#4]
I know that this was supposed to be fixed in this commit:

https://github.com/phuu/sparksvg/commit/50440d74f5cc313634f0d6f999dcf152ac3e2a1c

...but I'm still seeing gaps in the sparkline in Firefox when there are zero values in the dataset.

![sparklines](https://f.cloud.github.com/assets/18826/48559/79270a32-5913-11e2-944d-a0ecd34bbfb9.png)

**Comment by tgvashworth** [comment]
Hmm. Could you send me an example dataset?

**Comment by tgvashworth** [comment]
I swapped it into [this page](http://thesession.org/members/83374) and got this:

![](http://i.phuu.net/M0U2/Screen%20Shot%202013-01-07%20at%2022.01.00.png)

My code is this:

``` html
<embed src="http://sparksvg.me/line.svg?13,0,0,13,0,13,13,0,38,0,13,38,13,13,0,13,0,13,0,0,0,25,0,0,0,0,0,0,50,0,0,0,25,13,0,0,13,0,13,0,0,13,50,0,13,0,0,0,13,0,13" width="100" height="15">
```

In [JS Bin](http://jsbin.com/uhicar/4).

**Comment by adactio** [comment]
I'm using the datasets on this page: http://thesession.org/members/1

```
<embed src="http://sparksvg.me/line.svg?50,4,0,1,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0" width="100" height="15"></embed>

<embed src="http://sparksvg.me/line.svg?50,20,5,5,0,5,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,5" width="100" height="15"></embed>

<embed src="http://sparksvg.me/line.svg?17,0,50,0,0,0,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17" width="100" height="15"></embed>

<embed src="http://sparksvg.me/line.svg?50,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0" width="100" height="15"></embed>

<embed src="http://sparksvg.me/line.svg?7,14,14,0,21,7,0,7,21,0,0,0,7,50,7,0,14,0,0,0,0,0,7,0,0,0,0,0,7,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,7,0,7,14" width="100" height="15"></embed>

<embed src="http://sparksvg.me/line.svg?50,20,7,9,15,22,11,17,15,8,11,11,11,21,10,9,13,3,4,2,4,3,4,1,6,3,1,5,2,2,3,0,2,1,1,1,1,3,2,2,1,1,1,1,0,1,0,2,1,4,18" width="100" height="15"></embed>
```

**Comment by tgvashworth** [comment]
I can't seem to replicate it. Do you see the issue on [this page](http://jsbin.com/iyeqiw/6) in Firefox?

**Comment by adactio** [comment]
Weird. I don't see it on that page, but it still happens if it put the sparklines on the actual page. I did some testing (fiddling around with the CSS and JavaScript on the same page), but it seems like the issue is intermittent: if I scroll down and back up again, or if I change the size of the browser window, the zero values appear and disappear.

So this is an odd one; very hard to reproduce but really annoying when it happens. :-(

**Comment by tgvashworth** [comment]
Hmm. And it's only in Firefox? Could you leave a page on the actual site using the SVGs so I can have a play?

**Comment by adactio** [comment]
I've created an alternate view page for member profiles on The Session: add /alt to the URL:

http://thesession.org/members/1/alt

I'm still seeing that odd effect in Firefox although, weirdly, if I scroll down and up again, the issue seems to fix itself temporarily ...and sometimes it doesn't appear at all. Most odd. Some kind of strange rendering quirk.

**Comment by tgvashworth** [comment]
Thanks Jeremy. Unfortunately I can't replicate it at all, except for at a very very narrow viewport size (less than 100px), and I can't figure out how to detach the Firefox dev tools to investigate.

My other thought is that this could be an OS level issue – I'm on Mountain Lion, how about you?

Firefox's SVG implementation is buggy in other areas too – like you can't get the height of the containing element when running the inline Javascript, but can in all other browsers, and I'll be looking for a solution to that soon – so I think this could be related. It's puzzling to say the least!

**Comment by tgvashworth** [comment]
@adactio Had a brief [tweet conversation](https://twitter.com/paulrouget/status/295841877486358528) with Paul Rouget, and he suggested it might be a retina issue – are you on a retina screen?

**Comment by adactio** [comment]
No, I'm on an older Macbook Air, also running Mountain Lion.

**Comment by tgvashworth** [comment]
Egads. It looks like it's only on your machine – have you tried it out in Firefox Nightly/Aurora?

This all suggests it'd be worth submitting a Firefox bug, as Paul said, but the problem is replicating it.

**Comment by adactio** [comment]
I can replicate it on my iMac at work. Pop 'round to the Clearleft office if you want to see it in action.
